### ISSUE TITLE
Infinite CSS prefixing when using a formatter

### ISSUE THREAD

**Issue by Archmonger** [mrmlnc/vscode-autoprefixer#130]
### Environment

* VS Code version: 1.53.2
* Autoprefixer plugin version: v3.0.1
* Operating System: Windows 10

### Actual behavior
[See here](https://gyazo.com/7a66260fbdb72589976d73406349b92c)

### Expected behavior
In order to prevent adding duplicates on every save, CSS AutoPrefixer should not consider the newline character when checking if a rule already exists. 

### Steps to reproduce
When using Format On Save for Prettier and CSS AutoPrefixer...
1. Enter a line of CSS that would cause Prettier to add indentation to CSS-AutoPrefixer's code
2. Click save

### Autoprefixer config

Default config, no modifications

### Code sample

```css
.viewport .poster {
	width: var(--poster-width);
	height: var(--poster-height);
	display: block;
	transition: filter 0.3s ease, transform 0.3s ease, opacity 2.5s;
	z-index: 6;
	position: relative;
}
```
