### ISSUE TITLE
Comments being converted from double-slash to star-slash

### ISSUE THREAD

**Issue by jhildenbiddle** [mrmlnc/vscode-autoprefixer#91]
Just installed v2.0.0 and noticed that double-slash comments are being converted to star-slash comments in sass/scss files by this extension.

Before:
```scss
// My comment
```

After:
```scss
/* My comment*/
```

This doesn't happen when using the Autoprefixer demo here: https://autoprefixer.github.io/. Perhaps updating the version of autoprefixer used by this extension from 6.5.0 (according the the `package.json` file) to the latest (7.1.2) will address the issue? If not, is there a setting that can be added to prevent this from happening?

Thanks!

**Comment by mrmlnc** [comment]
Hello, @jhildenbiddle,


For first time you can install `autoprefixer@7` and use `autoprefixer.findExternalAutoprefixer` from [setting](https://github.com/mrmlnc/vscode-autoprefixer#supported-settings).

I'll look into this issue soon.

**Comment by mrmlnc** [comment]
Should be resolved by [2.1.0](https://github.com/mrmlnc/vscode-autoprefixer/releases/tag/2.1.0).

**Comment by jhildenbiddle** [comment]
Thanks for the quick turnaroud, @mrmlnc .

Unfortunately, this does not appear to be resolved.

- I have disabled all VSCode extensions except for Autoprefixer
- I have upgraded the Autoprefixer extension to 2.1.1
- I have tried using an external version of autoprefixer by installing it via NPM and setting `autoprefixer.findExternalAutoprefixer` to `true` in VSCode
- I have verified that the issue is not related to autoprefixer by comparing the output of the extension and postcss-cli + autoprefixer

SCSS code:

```scss
// Top level comment

body {
    display: flex;
    // color: #000;
}
```

Processed using postcss-cli and autoprefixer:

```scss
// Top level comment

body {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    // color: #000;
}
```

Processed using VSCode wtih Autoprefixer plugin (2.0.0 & 2.1.1):

```scss
/* Top level comment*/

body {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    /* color: #000;*/
}
```

Thanks again for taking a look at this!
